global:
  # ignore edge weights?
  ignore_edge_weights: true
  sample_size: 250
  display_graph_stats: false

# reduce dimension?
dim:
  dimension: 100
  reduce_dimension: true
  # project at random?
  random_projection: false

# classifiers settings
classification:
  ada_n_estimators: 3000
  dtree_depth: 2
  rf_n_estimators: 3000
  # standardize? -> seems to improve accuracy of adaboost
  standardize: true
  # normalize?
  normalize: false

# use fingerprints?
fp:
  use_fp: false
  times:
    - 6

# use clusters?
cs:
  use_clusters: false

# use variance vector?
vv:
  use_var_vector: false

# bag of words model?
bow:
  use_bow: false
  # should we use word frequencies?
  bow_weights: false

